name: integration-test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: '${{ runner.os }}-pip-

            ${{ runner.os }}-

            '
      - name: Install core dependencies and package
        run: 'python -m pip install --upgrade pip

          if [ -f packages/requirements.txt ]; then pip install -r packages/requirements.txt;
          fi

          if [ -f packages/requirements-optional.txt ]; then pip install -r packages/requirements-optional.txt;
          fi

          pip install -e packages/fairchem-core[dev]

          pip install -e packages/fairchem-data-oc[dev]

          pip install -e packages/fairchem-demo-ocpapi[dev]

          pip install -e packages/fairchem-applications-cattsunami

          '
      - id: measurement-5
        name: Record Measurement After Install core dependencies and package
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install core dependencies and package
          task: get-measurement
      - name: Integration tests
        run: 'pytest tests/demo/ocpapi/tests/integration/ --skip-ocpapi-integration
          -c ./packages/fairchem-core/pyproject.toml

          '
      - id: measurement-7
        name: Record Measurement After Integration tests
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Integration tests
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    strategy:
      matrix:
        python_version:
          - '3.9'
          - '3.12'
      max-parallel: 10
