name: lint
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: 'python -m pip install --upgrade pip

          if [ -f packages/requirements.txt ]; then pip install -r packages/requirements.txt;
          fi

          if [ -f packages/requirements-optional.txt ]; then pip install -r packages/requirements-optional.txt;
          fi

          pip install -e  packages/fairchem-core[dev]

          '
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: ruff
        run: 'ruff --version

          ruff check src # tests has a lot of issues , TODO

          ruff format --check src # tests

          '
      - id: measurement-6
        name: Record Measurement After ruff
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: ruff
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    strategy:
      max-parallel: 6
