name: release
on:
  push:
    branches:
      - main

jobs:
  build:
    needs: test
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    uses: ./.github/workflows/build.yml
  docs:
    needs: test
    secrets: inherit
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    uses: ./.github/workflows/deploy_docs.yml
  release-applications-cattsunami:
    environment:
      name: pypi
      url: https://pypi.org/p/fairchem-applications-cattsunami/
    if: '( github.event.inputs.release-pypi == ''true'' && startsWith(github.ref_name,
      ''fairchem_applications_cattsunami-'') ) || startsWith(github.event.release.tag_name,
      ''fairchem_applications_cattsunami-'')

      '
    needs:
      - build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/download-artifact@v4
        with:
          name: dist-applications-cattsunami
          path: dist-applications-cattsunami
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist-applications-cattsunami/
          skip-existing: true
          verbose: true
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
  release-core:
    environment:
      name: pypi
      url: https://pypi.org/p/fairchem-core/
    if: '( github.event.inputs.release-pypi == ''true'' && startsWith(github.ref_name,
      ''fairchem_core-'') ) || startsWith(github.event.release.tag_name, ''fairchem_core-'')

      '
    needs:
      - build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/download-artifact@v4
        with:
          name: dist-core
          path: dist-core
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist-core/
          skip-existing: true
          verbose: true
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
  release-data-oc:
    environment:
      name: pypi
      url: https://pypi.org/p/fairchem-data-oc/
    if: '( github.event.inputs.release-pypi == ''true'' && startsWith(github.ref_name,
      ''fairchem_data_oc-'') ) || startsWith(github.event.release.tag_name, ''fairchem_data_oc-'')

      '
    needs:
      - build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/download-artifact@v4
        with:
          name: dist-data-oc
          path: dist-data-oc
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist-data-oc/
          skip-existing: true
          verbose: true
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
  release-demo-ocpapi:
    environment:
      name: pypi
      url: https://pypi.org/p/fairchem-demo-ocpapi/
    if: '( github.event.inputs.release-pypi == ''true'' && startsWith(github.ref_name,
      ''fairchem_demo_ocpapi-'') ) || startsWith(github.event.release.tag_name, ''fairchem_demo_ocpapi-'')

      '
    needs:
      - build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/download-artifact@v4
        with:
          name: dist-demo-ocpapi
          path: dist-demo-ocpapi
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist-demo-ocpapi/
          skip-existing: true
          verbose: true
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
  test:
    secrets: inherit
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    uses: ./.github/workflows/test.yml
