name: Close inactive issues and PRs
on:
  push:
    branches:
      - main

jobs:
  close-issues:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/stale@v9.1.0
        with:
          days-before-close: 14
          days-before-stale: 30
          exempt-issue-labels: dont-close
          exempt-pr-labels: dont-close
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: stale
          stale-issue-message: This issue has been marked as stale because it has
            been open for 30 days with no activity.
          stale-pr-label: stale
          stale-pr-message: This PR has been marked as stale because it has been open
            for 30 days with no activity.
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
