name: tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: '${{ runner.os }}-pip-

            ${{ runner.os }}-

            '
      - name: Install core dependencies and package
        run: 'python -m pip install --upgrade pip

          if [ -f packages/requirements.txt ]; then pip install -r packages/requirements.txt;
          fi

          if [ -f packages/requirements-optional.txt ]; then pip install -r packages/requirements-optional.txt;
          fi

          pip install -e packages/fairchem-core[dev]

          pip install -e packages/fairchem-data-oc[dev]

          pip install -e packages/fairchem-demo-ocpapi[dev]

          pip install -e packages/fairchem-applications-cattsunami

          '
      - id: measurement-5
        name: Record Measurement After Install core dependencies and package
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install core dependencies and package
          task: get-measurement
      - name: Install additional dependencies
        run: 'wget https://github.com/m3g/packmol/archive/refs/tags/v20.15.0.tar.gz

          tar -xzvf v20.15.0.tar.gz

          cd packmol-20.15.0

          ./configure

          make

          echo "$(readlink -f .)" >> $GITHUB_PATH

          '
      - id: measurement-7
        name: Record Measurement After Install additional dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install additional dependencies
          task: get-measurement
      - name: Test core with pytest
        run: 'pytest tests -vv --ignore=tests/demo/ocpapi/tests/integration/  --cov-report=xml
          --cov=fairchem -c ./packages/fairchem-core/pyproject.toml

          '
      - id: measurement-9
        name: Record Measurement After Test core with pytest
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Test core with pytest
          task: get-measurement
      - if: ${{ matrix.python_version == '3.12' }}
        name: codecov-report
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    strategy:
      matrix:
        python_version:
          - '3.9'
          - '3.12'
      max-parallel: 10
